"use client";

import { Badge } from "@/components/ui/badge";
import { FileText, TrendingUp } from "lucide-react";
import type { ResumeAnalysisResponse } from "@/app/(platform)/resume-analysis/resume-analysis.types";

interface ResumeMatchGaugeCardProps {
  analysis: ResumeAnalysisResponse;
}

export function ResumeMatchGaugeCard({ analysis }: ResumeMatchGaugeCardProps) {
  const details = analysis.extracted_details;
  const score = analysis.match_score;

  // Calculate SVG circular arc values
  const strokeDashoffset = 251.2 - (251.2 * score) / 100;

  return (
    <div className="rounded-2xl bg-card border border-border/70 p-6 sm:p-8 shadow-2xs flex flex-col md:flex-row md:items-center justify-between gap-6 w-full">
      <div className="space-y-3 flex-1 min-w-0">
        <div className="flex items-center gap-2.5 flex-wrap">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary shrink-0">
            <FileText className="h-5 w-5" />
          </div>
          <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-foreground truncate">
            {analysis.resume_filename}
          </h1>
          {details.seniority_fit && (
            <Badge className="bg-primary/10 text-primary border-primary/20 text-xs font-bold rounded-full px-3 py-0.5">
              {details.seniority_fit} Alignment
            </Badge>
          )}
        </div>

        <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
          {details.experience_match_summary || "Candidate experience match summary generated by AI Analysis engine."}
        </p>
      </div>

      {/* Circular Arc Match Gauge Box */}
      <div className="flex items-center gap-4 rounded-2xl bg-muted/40 p-4 sm:p-5 border border-border/40 min-w-[200px] shrink-0 justify-center">
        <div className="relative flex items-center justify-center">
          <svg className="h-20 w-20 -rotate-90 transform" viewBox="0 0 100 100">
            <circle
              cx="50"
              cy="50"
              r="40"
              className="text-muted stroke-current"
              strokeWidth="10"
              fill="transparent"
            />
            <circle
              cx="50"
              cy="50"
              r="40"
              className="text-primary stroke-current transition-all duration-1000 ease-out"
              strokeWidth="10"
              strokeDasharray="251.2"
              strokeDashoffset={strokeDashoffset}
              strokeLinecap="round"
              fill="transparent"
            />
          </svg>
          <div className="absolute flex flex-col items-center justify-center text-center">
            <span className="text-xl font-bold text-foreground leading-none">{score}%</span>
          </div>
        </div>

        <div className="flex flex-col text-left">
          <span className="text-xs font-bold text-foreground flex items-center gap-1">
            <TrendingUp className="h-3.5 w-3.5 text-primary" /> Overall Fit
          </span>
          <span className="text-[11px] text-muted-foreground mt-0.5">
            {score >= 80 ? "Strong Match" : score >= 60 ? "Moderate Fit" : "Potential Gaps"}
          </span>
        </div>
      </div>
    </div>
  );
}
